### ISSUE TITLE
Clicking in a normal-mode vim pane wreaks havoc

### ISSUE THREAD

**Issue by OJFord** [vercel/hyper#1291]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.1
- **Hyper.app version**: 1.0.0

## Issue
With vim in normal mode, clicking (e.g. to focus, but I do it frequently by accident) in that pane seems to enter a sequence of characters that causes some unwanted effect on the open document.

Usually, but not always, the `w`ord clicked on is searched for; often text is inserted, edited, or moved around, and sometimes code is (un)folded.

Needless to say, this is annoying and confusing; if the document wasn't definitely saved immediately prior (or only just opened) it takes care to unsure exactly the right amount of `u`ndos.

**Comment by jwhitley** [comment]
FWIW, I'm not able to replicate this in either normal mode or insert mode with:

* macOS: 10.12.2
* Hyper.app: 1.0.1

and one of:
* vim: 8.0 
* neovim: recent HEAD build at 29e6515

In both normal and insert, the cursor is placed at the mouse position as expected.  I can even hold and drag and have the cursor follow the mouse without spurious input into (neo)vim.  Perhaps test against Hyper 1.0.1, in case this issue was fixed already.  Otherwise perhaps there's some environmental difference between our setups that's triggering this problem?

**Comment by chrisnojima** [comment]
In my experience it's inconsistently reproducible. Some sessions it's constant and almost unusable. Other times it works correctly.

**Comment by jwhitley** [comment]
@chrisnojima Good to know. I haven't yet flipped to using Hyper full-time, mostly due to this issue, so my testing has been very limited.  I'll try to put it into heavier use and see if I can replicate.

**Comment by chrisnojima** [comment]
I'll try also. Due to an unrelated high cpu usage bug I've had to abandon
using hyper as my primary terminal.

**Comment by therealplato** [comment]
This should probably be closed as dupe of https://github.com/zeit/hyper/issues/95

**Comment by OJFord** [comment]
@therealplato It is similar, but the title of #95 should then at least be changed to expand the scope to all mouse events I suppose. It would seem a little strange that @jwhitley posted there in agreement and here to say he cannot reproduce the issue though. Strange both to view if merged, and as evidence against it being the same underlying issue.

To be honest, this and another issue have stopped me using Hyper at least for the time being, so I won't dig further into this at the moment.

**Comment by jwhitley** [comment]
@OJFord I just retested.  On Hyper v1.0.1, the last I'd tried, clicking and mouse scrolling was (still) working great for me in neovim.  Then I accepted the upgrade to latest shipping, v1.3.1 at this writing. At first, mouse-scrolling produced a "reproducible once" issue where it flipped nvim into insert mode and started blasting junk into the buffer  (imagine an nvim "DOOM-nailgun-of-letter-A" plugin.  :-pppppp )

On subsequent attempts, I noticed that mouse-click-to-position-cursor does nothing; it's as if I didn't click at all.  Mouse scrolling worked, and didn't enter insert mode, but seemed "jankier" in a way between the trials, and relative to my brief test of v1.0.1, resurrected some form of the bounce-at-buffer-ends issues I've seen before.  Mouse scroll to the top or bottom end of a file should just stop at some point, not "bounce back" a little.

It's possible that there's some kind of race condition going on here.  Maybe my Mac is consistently a touch faster (or slower! esp. due to other input-related stuff running on my system.) than other testers here, and that's partly shielding me from seeing the worst this bug has to offer.  Still, Hyper's not yet into robust, usable territory for me either.

**Comment by OJFord** [comment]
I haven't used Hyper for a few years at least, and it seems to be on v3.x rather than v1.x when I reported this, so I think despite a few other people showing interest and having the issue too, I'll assume it's fixed and close. (I'll gladly re-open if it's still an issue for anyone, just @ ping me.)
