### ISSUE TITLE
Hyper doesn't correctly handle variable-width characters

### ISSUE THREAD

**Issue by wyqydsyq** [vercel/hyper#1857]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OpenSUSE Tumbleweed
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/wyqydsyq/69b2dae557654799c91cfd6249ab10d7
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Hyper doesn't correctly handle variable-width characters, namely, emojis from the "noto-emoji" font. This issue is also prevalent in libvte and some Qt based terminal emulators. It works in the `st` emulator which apparently uses a different `wcwidth` implementation.

Here's a comparison between my same Tmux session looking broken in Hyper and appearing as it should in st:
![image](https://cloud.githubusercontent.com/assets/621277/26292931/5dcac43e-3efd-11e7-8428-fc3c732a12d0.png)

You can also see that the spacing on the tmux pane title is messed up, strangely resizing the window sometimes fixes this unpredictably.

**Comment by rauchg** [comment]
Thanks for the report. I believe @tibotiber is currently looking into this, and his PR is very close!

**Comment by tibotiber** [comment]
@wyqydsyq would you mind trying the code on #1536 to confirm if it fixes your issue?

**Comment by revelt** [comment]
We've got a bit of a mixup: #1536 talks about more about powerline, but comments mention emoji as well. This issue is titled as to cover quite wide base, including plain emoji, but then talks specifically about emulators and issues shown are not regarding the characters but the UI of the emulator.

So, since emoji is "variable-width", it also falls into this issue, I mean things like:

![hyper_unicode](https://user-images.githubusercontent.com/8344688/27726558-cf869d9e-5d72-11e7-8bbf-e5bff42373e8.gif)

I would help to test @tibotiber question above but I have no clue how to get the emulators in question set up. @wyqydsyq please follow up to Thibaut's question.

**Comment by Borkason** [comment]
Windows 10 version 1709, Hyper 1.4.8

Display problem with emoji's: 🎆🎆🎆🎆🎆

![grafik](https://user-images.githubusercontent.com/2971735/34495629-5cdf5c92-eff6-11e7-9f68-19da2b1fbf85.png)

Notice the cursor when repeating the last command with ARROW KEY UP.

**Comment by wyqydsyq** [comment]
Sorry for the late reply, I stopped using Hyper due to this issue. I just tried the latest version which apparently has #1536 merged, however still get undesirable results. Screenshot attached shows a comparison with the display from Tilix which is how it should look.

![image](https://user-images.githubusercontent.com/621277/34505469-f0a06488-f070-11e7-8757-1c5d89008a71.png)

**Comment by Stanzilla** [comment]
Should be https://github.com/xtermjs/xterm.js/issues/1059

**Comment by ghostrick** [comment]
similar problem occurred on v3.0.2

**Comment by jquast** [comment]
I actually used hyper as an example in an article I wrote about varying Unicode Version level support in Terminals (and a solution that works for python), https://jeffquast.com/post/terminal_wcwidth_solution/

The gist of it is that Hyper supports only version ``5.1.0`` of the Unicode standard for wide characters, through its depenency on the wcwidth library, whereas version 9.0 introduces the specification of Emoji's, from the article above,

> Chinese, Japanese, and Korean users, whose languages use full-width characters almost exclusively have been the most impacted by this problem, whereas the Western world only seemed to notice it with the introduction of emoticons in Unicode version 9.0.

The problem is the depenency on the wcwidth library, that library does not support any newer version. I haven't yet found a javascript version that has been brought up-to-date (Latest Unicode specification is version ``13.0``)

best wishes !!

**Comment by LabhanshAgrawal** [comment]
@wyqydsyq @jquast can you check again with the latest [ci build](https://github.com/vercel/hyper/actions/runs/145055527)
I ran the `ucs-detect` tool with the new changes and it showed `UNICODE_VERSION=12.1.0; export UNICODE_VERSION`

**Comment by jquast** [comment]
<img width="598" alt="Screen Shot 2020-06-23 at 11 18 30 PM" src="https://user-images.githubusercontent.com/972584/85495132-f30b6e80-b5a7-11ea-8a45-c82a2118251c.png">

Everything looks great now, thanks

**Comment by LabhanshAgrawal** [comment]
> <img alt="Screen Shot 2020-06-23 at 11 18 30 PM" width="598" src="https://user-images.githubusercontent.com/972584/85495132-f30b6e80-b5a7-11ea-8a45-c82a2118251c.png">
> 
> Everything looks great now, thanks

What is this tool you're using?

**Comment by jquast** [comment]
`pip install wcwidth blessed`

then, this is the script: https://github.com/jquast/wcwidth/blob/master/bin/wcwidth-browser.py
