### ISSUE TITLE
Unfocus term when window is unfocused

### ISSUE THREAD

**Issue by chabou** [vercel/hyper#2738]
In 2.0.0-canary.14, cursor is not unfocused when window become unfocused.

**Comment by Jacfem** [comment]
@chabou hey there, I'd love to tackle this issue (first time with this project!). I'm a bit curious though what the inactive state should look like, because when trying to run an older version of canary (tried 2.0.0-canary.13 at least), it appears the same as the latest, which is the following session, top being the active, focused window & bottom being the unfocused window. Is there a general type of 'faded' look you'd like? Thanks!

<img width="724" alt="screen shot 2018-04-16 at 9 32 32 pm" src="https://user-images.githubusercontent.com/15792886/38843603-d15dab82-41bd-11e8-86fb-97ff1892eef6.png">

**Comment by sumukhah** [comment]
Hello There,
I am a first-time-contributor,
Can i take this?

**Comment by koenvg** [comment]
Hey, I just checked if this is still an issue and this seems to be fixed.
The version I checked it with 3.0.2
os: Mac

**Comment by chabou** [comment]
Thank you 🙏
