### ISSUE TITLE
OpenSSH Cli.. window displayed after Hyper window resize

### ISSUE THREAD

**Issue by azamat-jamaliev** [vercel/hyper#3010]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`
## Issue
1. Connect to ssh device using: 
> ssh root@mybooklive.local
2. Resize the Hyper.app window

Result: "OpenSSH Cli.." window displayed:
<img width="760" alt="screen shot 2018-05-12 at 08 32 31" src="https://user-images.githubusercontent.com/6066564/39954006-6fb544a6-55bf-11e8-8da6-ccc9ddd3a40e.png">
 
It seems the issue relates with this one: https://github.com/PowerShell/Win32-OpenSSH/issues/1109
in OpenSSH

**Comment by Toweoner** [comment]
Hello, Do you know how to fix this issue?

**Comment by LabhanshAgrawal** [comment]
It's due to earlier limitations on windows. `node-pty` had to open a console window offscreen and read from that. It's been fixed since the addition of `conpty` on windows.
It's not being used in earlier hyper versions.
So you should download the [ci build](https://github.com/vercel/hyper/actions/runs/157826845) and try that out, it has support for conpty.
