### ISSUE TITLE
Why colors in vim became more colder under hyper.is comparing to gnome terminal?

### ISSUE THREAD

**Issue by inoyatov** [vercel/hyper#3066]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04 LTS 64 bit
- **Hyper.app version**: Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/inoyatov/c51d39b983dc2986dd0b29b3244f5dec

## Issue
I am using gruvbox color theme for vim from [here](https://github.com/morhetz/gruvbox). In gnome terminal everything works fine however under hyper terminal colors become colder. I provide pictures in order to demonstration issue below:
![Vim in Hyper Terminal](https://user-images.githubusercontent.com/7060390/40830521-a4f43e4e-65c1-11e8-91bb-d2921e60090a.png)
![Vim in Gnome Terminal](https://user-images.githubusercontent.com/7060390/40830522-a522de3e-65c1-11e8-89a1-63e7f3a14fe5.png)

So, what is the problem? How it can be fixed?
P.S: I am ready to provide related information if necessary.

**Comment by inoyatov** [comment]
I installed VSCode with Gruvbox them from [here](https://github.com/jdinhify/vscode-theme-gruvbox) and tried to access to same file using integrated terminal output is same with hyper terminal.

![vscode](https://user-images.githubusercontent.com/7060390/40831737-c144089c-65c4-11e8-9095-2e4abae5f2e3.png)

**Comment by LabhanshAgrawal** [comment]
The `colors` in your config are different from the ones in the default [config](https://github.com/vercel/hyper/blob/712a19081df7954a7fbf6bab4522de4a24def9fd/app/config/config-default.js#L78), maybe it's because of that

closing as this is for v2 and earlier, please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this problem with the new build.
