### ISSUE TITLE
Syntax color not preserved as non-root user

### ISSUE THREAD

**Issue by funnymania** [vercel/hyper#3249]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.1.0-canary.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/funnymania/cc4a456ec40fe6db93628a249476ac25
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A

## Issue

In Bash (WSL), when switching from root to another user, syntax colouring disappears. 

Switching back to root brings it back. 

![syntax-silencio](https://user-images.githubusercontent.com/36145527/46702044-8b946c00-cbd6-11e8-8d04-f9dad20319f0.PNG)

**Comment by LabhanshAgrawal** [comment]
you can test by printing something with color escape sequences
e.g. `echo -e '\e[31m 767M \e[41m_______\e[m \e[31mdir1/\e[m'` (try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/545727436#artifacts))
this seems to be because of the profile not getting sourced on just doing `su`
