### ISSUE TITLE
Context menu is showing Hyper but throws an error when clicked

### ISSUE THREAD

**Issue by turkeyphant** [vercel/hyper#3564]
* [X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
* [X ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
 
* **OS version and name**: Windows 10 Enterprise 64bit 1809 Build 17763.379
* **Hyper.app version**:  2.1.2
* **Relevent information from devtools**: N/A
* **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
The context menu item: `Open Hyper Here` doesn't work when clicked in partitions other than where the software is installed. I read the issues #1305 #1314, #1133 and #1283 but the fixes don't work.

I get the following error:
 
**Explorer.exe**
> This file does not have a program associated with it for performing this action. Please install a program or, if one is already installed, create an association in the Default Programs control panel.

I have tried complete reinstalls and reboots using Chocolatey and CCleaner.
I have checked the registry.

Weirdly it works if I right click on the Desktop but not if I right click on the Desktop folder (or indeed any other folder) through Explorer.

**Comment by scytalezero** [comment]
I'm seeing this same issue.

**Comment by hashchange** [comment]
I've had problems with this forever and more or less abandoned Hyper because of it.

After finally moving to Windows 10, I've had a closer look at the issue. As far as I can tell, the problem here is a missing registry key.

Hyper creates the following key:

`Computer\HKEY_CLASSES_ROOT\Directory\Background\shell\Hyper`

and that's not enough. I have recreated the exact same key in

`Computer\HKEY_CLASSES_ROOT\Directory\shell\Hyper`

and things suddenly work. :)

Unfortunately, the icon and command paths are version-specific, so installing a Hyper update will break the context menu again until the paths are readjusted.
