### ISSUE TITLE
Emoji gets glitched when pasted into the terminal

### ISSUE THREAD

**Issue by vaporwavie** [vercel/hyper#3615]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 29
- **Hyper.app version**: 3.0.0 Stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/vaporwavie/018814c8d1e55e9e1a3f21b9cb7cca50
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Hey, what's up!

I've just installed Hyper 3 on my machine, as I got *hyped* for the new features and everything. Although, when I pasted an emoji into it, I've experienced some weird glitch. Here is the screenshot: https://i.imgur.com/k5PMysR.png

Additional: If I split the screens, the glitch disappears.

Cheers!

**Comment by lucasea777** [comment]
same thing, Ubuntu 18.04, but this also happens to me in hyper-2.1.1...

**Comment by alexdevero** [comment]
The same on windows, using default Window emoji picker _(Win + . )_.

Text:
`Hello 😀`

Result:
`Hello �`

**Comment by minvedacat** [comment]
this should be upstream issue, since xterm.js has this sort of staff for 2 years
https://github.com/xtermjs/xterm.js/issues/469
https://github.com/xtermjs/xterm.js/issues/1059
https://github.com/xtermjs/xterm.js/issues/1709

Even vscode has same issue due to xterm.js lack of ability to render these emoji part of unicode, as far as I know, it is now blocking many issues and they need here there.

**Comment by LabhanshAgrawal** [comment]
fixed in canary
