### ISSUE TITLE
Setup/Use Hyper as default terminal instead of CMD on windows 

### ISSUE THREAD

**Issue by Abu3safeer** [vercel/hyper#3677]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 64 bit Build 17763
- **Hyper.app version**: 3.0.2 Stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:I use Windows binary
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Go to System environment, set ComSpec to Hyper.exe file, save then try running any .bat file. 

## Issue

Hello all, I like how Hyper look (though it has some issues with RTL languages).

What I want to do is to make hyper runs by default when using .bat file, by default windows uses CMD, but I want to use Hyper.

so I go to Windows environments variables and set ComSpec to Hyper.exe directory.
![image](https://user-images.githubusercontent.com/12091003/57822761-a39c2180-779d-11e9-8670-d25b08757546.png)
to
![image](https://user-images.githubusercontent.com/12091003/57822784-bf9fc300-779d-11e9-87a1-6c8fd0e6a9e8.png)

but the window never show up.

I think this is because hyper thinks bat file should use one of these:
![image](https://user-images.githubusercontent.com/12091003/57822881-24f3b400-779e-11e9-9745-9ead3de1418e.png)

What I trying to run is an npm package called cr-dl
the content of the bat is like this?:
hyper cr-dl download <Link-GOES-HERE>

**Comment by shmediaproductions** [comment]
hyper doesn't just "think" bat files should use one of hyper's commands. these are the only commands that exist in hyper.exe, that's how it's written. hyper alone can not interpret arguments intended for the shells it emulates. i don't think you can pass cmd.exe's launch arguments to hyper externally without using the config file. it only has a limited set of its own commands, the ones you see in your screenshot of the help menu. none of these actually execute code specific to a command line, bencause hyper is just a command line interface. when you actually use the program, all you are doing is typing text into a GUI and the program hooks into whatever shell you have selected and passes along the input. all of the actual parsing of your arguments is handled by the shell itself, not by hyper. this alone wouldn't be a problem except that hyper doesn't have a very robust set of launch arguments for itself. a --input command could have worked, then you'd be able to define a shortcut as "C:\path\to\hyper.exe --input" and use the shortcut plus whatever input method you choose to basically launch hyper with the input you chose. but hyper doesn't seem to have this feature. neither do any other popular CLIs that i'm aware of.

as it is, there might be a plugin that adds this functionality. if not, there might be a way to dynamically send launch arguments to hyper by modifying the .hyper.js config file in real-time via javascript or something. that is a pretty dirty solution, not something you would literally want to use as a definition for comspec lol. but it should be possible, since there IS a default launch arguments section in the config file. so, your script could work by hooking into all the layers that normally send commands to %ComSpec% or cmd.exe, and instead redirecting the commands to a small script that edits them into .hyper.js' launch arguments section, saves the file, then launches hyper.exe from the user's lnk shortcut. like i said, pretty dirty. but unless you are sending a whole lot of commands per second from outside the CLI, or are running a HDD boot volume or doing something else that slows down file operations, you shouldn't actually notice a difference. it doesn't take that long to update and save a text file, and hyper.exe already launches pretty slowly compared to cmd.exe.

honestly, fwiw, i'd just give up on the dream. i was looking into something similar with windows terminal pretty recently, trying to do pretty much the same thing. i would never suggest trying to redefine comspec to any CLI, that has the potential to really mess your system files up during software updates. but i was definitely interested in using the new windows terminal in place of cmd/psh for all user-initiated, visible console windows. since there are only a few ways i ever open console windows *while* passing arguments from outside cmd.exe, i thought it'd be pretty easy. namely batch files, shortcut files, autohotkey and rainmeter modules. but getting any one of these to work is flat out impossible without major changes to the source code. they are supposedly working on this now but it's not easy to implement apparently. and with windows terminal you don't even get a "launch arguments" section in the config file so there's really no way to do it without modifying the source code or injecting the executable with your own code. i've heard that the only reason you can do this with cmd is because the shell host is already attached to cmd console. it sounds implausible, so who knows for sure. but i don't think you'll find a nice looking CLI substitute that works for batch files and shortcuts, at least until windows terminal gets that vaguely possible update. if there is one out there though, what you're looking for is not something that can interpret any commands. then it would have to basically contain cmd.exe itself, and then it's not much of a multipurpose shell emulator. you're looking for a shell emulator with a --input command. could be called anything, i'm just talking about a launch argument for the program itself that holds the launch argument's escaped content in memory until the console container is launched, then auto inputs the content into the default console input field. just keep in mind that even if you do find that, it's still pretty dirty compared to cmd.exe and if you actually replace comspec with something like that, you might have programs which were written in such a way that file operations could really mess something up.
