### ISSUE TITLE
Work on re-enabling WebGL renderer

### ISSUE THREAD

**Issue by Stanzilla** [vercel/hyper#3849]
During https://github.com/zeit/hyper/pull/3830 we disabled the WebGL renderer. This ticket is to track what is needed to do before we can re-enable it.

**Comment by GitSquared** [comment]
The WebGL renderer was disabled with the xTerm 4 PR because enabling it causes this output:

![Screenshot_20191007_104700](https://user-images.githubusercontent.com/24496417/66297417-28b7dc80-e8df-11e9-922e-60279a2f2223.png)

There are also some problems with text rendering. I'm unsure of what's causing this, and haven't tested it on Windows/macOS.

**Comment by ivanwonder** [comment]
Maybe we can pick this up with the [new release](https://github.com/xtermjs/xterm.js/releases/tag/4.3.0) of xterm.
https://github.com/microsoft/vscode/blob/35a8880109f28bbfc1dcc9f5305d32c195b60897/package.json#L56

**Comment by Stanzilla** [comment]
worth testing in any case

**Comment by LabhanshAgrawal** [comment]
Closing this as we have re-enabled the webgl renderer.
