### ISSUE TITLE
This solution fixed it for me.

### ISSUE THREAD

**Issue by w1ll-dev** [vercel/hyper#4147]
This solution fixed it for me.
https://github.com/zeit/hyper/issues/2144#issuecomment-326741620

_Originally posted by @esdotzed in https://github.com/zeit/hyper/issues/3586#issuecomment-489795443_

**Comment by Luxcium** [comment]
PROMPT_SP <D>
Attempt to preserve a partial line (i.e. a line that did not end with a newline) that would otherwise be covered up by the command prompt due to the PROMPT_CR option. This works by outputting some cursor-control characters, including a series of spaces, that should make the terminal wrap to the next line when a partial line is present (note that this is only successful if your terminal has automatic margins, which is typical).

When a partial line is preserved, by default you will see an inverse+bold character at the end of the partial line: a ‘%’ for a normal user or a ‘#’ for root. If set, the shell parameter PROMPT_EOL_MARK can be used to customize how the end of partial lines are shown.

NOTE: if the PROMPT_CR option is not set, enabling this option will have no effect. This option is on by default.

> This solution fixed it for me.
> [#2144 (comment)](https://github.com/zeit/hyper/issues/2144#issuecomment-326741620)
> 
> _Originally posted by @esdotzed in [#3586 (comment)](https://github.com/zeit/hyper/issues/3586#issuecomment-489795443)_

PROMPT_SP <D>
Attempt to preserve a partial line (i.e. a line that did not end with a newline) that would otherwise be covered up by the command prompt due to the PROMPT_CR option. This works by outputting some cursor-control characters, including a series of spaces, that should make the terminal wrap to the next line when a partial line is present (note that this is only successful if your terminal has automatic margins, which is typical).

When a partial line is preserved, by default you will see an inverse+bold character at the end of the partial line: a ‘%’ for a normal user or a ‘#’ for root. If set, the shell parameter PROMPT_EOL_MARK can be used to customize how the end of partial lines are shown.

NOTE: if the PROMPT_CR option is not set, enabling this option will have no effect. This option is on by default.

**Comment by Luxcium** [comment]
> This solution fixed it for me.
> [#2144 (comment)](https://github.com/zeit/hyper/issues/2144#issuecomment-326741620)
> 
> _Originally posted by @esdotzed in [#3586 (comment)](https://github.com/zeit/hyper/issues/3586#issuecomment-489795443)_

PROMPT_SP <D>
Attempt to preserve a partial line (i.e. a line that did not end with a newline) that would otherwise be covered up by the command prompt due to the PROMPT_CR option. This works by outputting some cursor-control characters, including a series of spaces, that should make the terminal wrap to the next line when a partial line is present (note that this is only successful if your terminal has automatic margins, which is typical).

When a partial line is preserved, by default you will see an inverse+bold character at the end of the partial line: a ‘%’ for a normal user or a ‘#’ for root. If set, the shell parameter PROMPT_EOL_MARK can be used to customize how the end of partial lines are shown.

NOTE: if the PROMPT_CR option is not set, enabling this option will have no effect. This option is on by default.

**Comment by hk4140** [comment]
> > This solution fixed it for me.
> > [#2144 (comment)](https://github.com/zeit/hyper/issues/2144#issuecomment-326741620)
> > _Originally posted by @esdotzed in [#3586 (comment)](https://github.com/zeit/hyper/issues/3586#issuecomment-489795443)_
> 
> PROMPT_SP 
> Attempt to preserve a partial line (i.e. a line that did not end with a newline) that would otherwise be covered up by the command prompt due to the PROMPT_CR option. This works by outputting some cursor-control characters, including a series of spaces, that should make the terminal wrap to the next line when a partial line is present (note that this is only successful if your terminal has automatic margins, which is typical).
> 
> When a partial line is preserved, by default you will see an inverse+bold character at the end of the partial line: a ‘%’ for a normal user or a ‘#’ for root. If set, the shell parameter PROMPT_EOL_MARK can be used to customize how the end of partial lines are shown.
> 
> NOTE: if the PROMPT_CR option is not set, enabling this option will have no effect. This option is on by default.

I had the issue, both on upgraded macOS Catalina and clean-installed one. PROMT_SP treatment solved the issue; no problem now, other than a few empty lines on Hyper startup.. 🙂

**Comment by Luxcium** [comment]
I forgot to mention my source: [PROMPT_SP](https://zsh.sourceforge.net/Doc/Release/Options.html#Prompting) on https://zsh.sourceforge.net/
