### ISSUE TITLE
Every command triggering configuration reload.

### ISSUE THREAD

**Issue by joe-scotto** [vercel/hyper#4318]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.15
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/joe-scotto/a751b47f54064c94ecc630994d98f0a6
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Any command I type, Hyper reloads the configuration. I had to recently reinstall xcode-tools and have found that any command I run triggers this reload. It happens if I run it from hyper or terminal.

**Comment by brodybits** [comment]
Fix the title, please

**Comment by joe-scotto** [comment]
@brodybits Fixed.

**Comment by Jonic** [comment]
I have the same issue - Hyper triggers a notification and a sound every single time I run a command, and it's gotten really annoying!

**Comment by the-ult** [comment]
I disabled/removed `hypercwd` this seems to fix the issue.

there was an error/warning that the hyper config was missing configuration settings for hypercwd. (adding the proper settings might help as well)

**Comment by LabhanshAgrawal** [comment]
Can you all try the latest [ci build](https://github.com/vercel/hyper/actions/runs/145055527) once and see if it works.

**Comment by the-ult** [comment]
Same issue is occuring. The latest does not seem to fix the problem. 
(screenshot has 3.0.2 again.. removed the. canary build since it had issues with the font as well.)

<img width="392" alt="Screenshot 2020-06-27 at 12 58 33" src="https://user-images.githubusercontent.com/4863062/85920672-ea4fbc80-b875-11ea-92ae-d6d30959bc2b.png">

**Comment by LabhanshAgrawal** [comment]
can you try these steps once -
close hyper
backup the config somewhere else
delete the config file
open latest hyper - config will be recreated (if you have problems with fonts, set `disableLigatures: true` in the newly generated config)

Also a question, config gets reloaded when it's accessed or modified, via the node fs.watchFile. Is there any process which might be accessing it like indexer or something. Also is it maybe a symlink currently>

**Comment by the-ult** [comment]
Hey @LabhanshAgrawal ,

Just completely removed Hyper (both stable and canary.)
Clean config.

It is still happening.
On every command (`ll`, `ls`, `npm outdated` etc)

-------------
Had the config opened in VS Code.. but closed it... (both the file and VS Code). And it is still happening.
It is happening on Mac when you switch desktops as well. But only sometimes
------------
Opened XCode, so it would install all extra dependencies etc.
------------

The Dev console does not show any errors.

<img width="286" alt="Screenshot 2020-06-27 at 15 36 31" src="https://user-images.githubusercontent.com/4863062/85923524-fcd4f080-b88b-11ea-9a08-93218c67a519.png">

**Comment by LabhanshAgrawal** [comment]
@the-ult 
Can you try a build from https://github.com/LabhanshAgrawal/hyper/actions/runs/151171792
I've changed the code to watch the config file to use `chokidar` instead of `fs.watch` directly.
Do try it out for a while to make sure there are no other issues or crashes
we'd moved from chokidar to fs.watch earlier due to crash reports, but that was almost 2 years ago, so chokidar should've improved in the meantime.

**Comment by the-ult** [comment]
```
❯ hyper version
3.1.0-canary.4

❯ hyper ls
hyper-one-dark
hyper-font-ligatures
hyperminimal
hyperborder
hyper-pane
hyper-tab-icons
hyper-quit
```
So far it seems to work. 👍

**Comment by LabhanshAgrawal** [comment]
Good to hear that, Do reply if you face any issue. If it goes well, I'll add a pr to use chokidar in a few days.

**Comment by LabhanshAgrawal** [comment]
> @the-ult
> Can you try the build from [LabhanshAgrawal/hyper/actions/runs/151171792](https://github.com/LabhanshAgrawal/hyper/actions/runs/151171792)
> I've changed the code to watch the config file to use `chokidar` instead of `fs.watch` directly.
> Do try it out for a while to make sure there are no other issues or crashes
> we'd moved from chokidar to fs.watch earlier due to crash reports, but that was almost 2 years ago, so chokidar should've improved in the meantime.

@joe-scotto @Jonic can you also try this build please? It will help us to confirm that this works and then can be merged.

**Comment by Jonic** [comment]
@LabhanshAgrawal I got a new Mac recently, and I haven’t seen the issue since, so I don’t think I’ll be much help testing the build!

I can install it anyway if you think that will actually be helpful, but I won’t be able to confirm whether or not this exact issue has been addressed!

**Comment by LabhanshAgrawal** [comment]
@Jonic it will certainly help if you can try this build.
As I've mentioned, last time we were using `chokidar` it caused crashes, so we moved to `fs.watch` #2217
Though that was almost 3 years (mistakenly wrote 2 earlier) ago. I want to confirm that it's not an issue now.

**Comment by LabhanshAgrawal** [comment]
@the-ult @Jonic 
Did you face any issues with the build?
If it worked well I'll open a pr for it.

**Comment by the-ult** [comment]
Did not face any issues 👍

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by the-ult** [comment]
Any change on a new release of hyper.js with this fix?

**Comment by Jonic** [comment]
@LabhanshAgrawal I know this has been closed, and the PR merged etc, and other issues about the same thing have opened and closed, but I'm still getting this issue. I'm running `3.1.0-canary.4`, and it's actually worse now than it ever has been!

I can see that the repo is still being updated, but there hasn't been an update since May 2019, so I'm just wondering if Hyper actually has a long-term future? I appreciate that it's a lot of work maintaining something like Hyper, but the config reloaded notification is making it an annoying experience, so hopefully we'll see 3.1 soon and this bug will be squashed once and for all!

Let me know if it would be useful to see my config, or if you'd like to hop on a screenshare some time to see the issue in action :)

**Comment by LabhanshAgrawal** [comment]
@Jonic well that release was before the fix for this got merged. We couldn't really do any releases since then as the code signing cert had expired and we're just trying to get vercel to update it.
I do hope we can start releasing soon.

Is there anything 'different' about your config? like maybe it's a symlink or something? I don't really know if the contents of the config can cause something like this. We mainly moved to chokidar as it's better than rolling our own hacky solution. And that somehow solved it.
