### ISSUE TITLE
Releases / public roadmap?

### ISSUE THREAD

**Issue by robcresswell** [vercel/hyper#4727]
Hi! I was looking at Hyper, but its very difficult to understand whether the project is alive or not. There are almost 700 commits since the last stable release, and over 300 since even the last canary release. There's no project board, and the issue milestones listed for `3.1.0` and `3.2.0` are so minimal that they are basically placeholders.

Is the project still being maintained and published, or should I be looking elsewhere?

**Comment by LabhanshAgrawal** [comment]
The releases had been paused due to some cert issues. @timothyis is setting up the certs, hopefully we'd be able to release soon.

3.1.0 milestone was populated by issues which were blocking the release, but the cert issue cropped up before the release.
Few of the webgl renderer related issues were pushed to 3.2.0 milestone, so that's somewhat like a placeholder currently.

Contributions are welcome, feel free to open issues & pr's

**Comment by robcresswell** [comment]
@LabhanshAgrawal Great, thanks, that's good to know! I'll close the issue
