### ISSUE TITLE
[enhance][bug] Tabs positions compatibility(anomaly) and QUIT ALERT

### ISSUE THREAD

**Issue by jukrb0x** [vercel/hyper#5166]
# Latest update
After fully re-install hyper, I found the tabs issue is not from hyper itself instead maybe some plugins caused them, still working on it. But still, quit alert can be a feature to be added.

The problem seems to be caused by multiple themes, **the theme management looks super bad for hyper.** every time I type `hyper i <theme-name>` and it maybe just cover the theme exist and everything mess up, any solution for this?

And the project seems to be long out of date, at least the latest release is dated in 2019.

![image](https://user-images.githubusercontent.com/15688641/102112418-9dd35a00-3e72-11eb-9f67-a461dfc85938.png)

# Info
```json
plugins: [
        "hyper-search",
        "hyperterm-paste",
        "hyperlinks",
        "hyper-quit",
        "hyperalfred",
        "hyper-drop-file",
        "hyper-sync-settings",
        "git-falcon9",
        "hyper-firewatch"
    ],
```

```
❯ hyper version            
3.0.2
```

# Quit Alert
I found that hyper doesn't support an alert popup when quitting it, it may cause some unnecessary cost if users accidentally quit the app.

An example of popup from iterm2:

![image](https://user-images.githubusercontent.com/15688641/102109166-b9d4fc80-3e6e-11eb-920b-1ee48424d88b.png)

# Tabs position anomaly
> _Not caused by hyper itself._

When opening multi-tabs of the shell, the arrangement of tabs seems not so ok. the traffic buttons covered the most left tab.

![image](https://user-images.githubusercontent.com/15688641/102109945-91013700-3e6f-11eb-9540-ad557e6e4282.png)

**Comment by jukrb0x** [comment]
whatever, world's changed.

**Comment by LabhanshAgrawal** [comment]
There's a separate issue already about the quit alert thing
We don't really have a way to distinguish between themes and other plugins at the moment, if you install multiple themes, they get applied on top of each other, so it's possible you get mixups somewhere.
The tab position issue is not from Hyper, but most likely from some plugin which is decorating the tab bar.
There hasn't been any release since quite long but there are updates to the codebase, if you want to try out the latest build, you can get it from the [ci](https://github.com/vercel/hyper/actions/runs/653628191#artifacts)
