### ISSUE TITLE
long links don't work

### ISSUE THREAD

**Issue by chovy** [vercel/hyper#5208]
Long links in irssi don't copy the whole url when clicked, it only copies the first line.

**Comment by Soomootie** [comment]
Hello, i try to write an url over three lines and it's working.
But it's seems some patterns doesn't work properly, like `https://github.com/vercel/hyper/tree/master\=id.poc`.

**Comment by LabhanshAgrawal** [comment]
I'm guessing that when you post long urls in irssi they are wrapped and indented which would cause issues when matching for links
@chovy can you provide any example screenshots so that we can confirm the cause.

**Comment by chovy** [comment]
https://ufile.io/vastf1zx

**Comment by LabhanshAgrawal** [comment]
To detect the links, text is read from buffer and matched using regex.

![Screenshot 2021-02-08 at 14 14 33](https://user-images.githubusercontent.com/16598275/107196828-20af0600-6a19-11eb-99fb-366f0c720844.png)
In your case, it's an ncurses application and there are other things in the second and third line (marked in screenshot) e.g. spaces
it's not regular text which is getting wrapped due to length
so, we can't detect that
you can open a separate issue about the parentheses problem
