### ISSUE TITLE
Hyper built from repository

### ISSUE THREAD

**Issue by igmt-official** [vercel/hyper#6409]
I built hyper from your repository, I'm using npm to built in just like in your instruction, instead of yarn i use npm

$ npm i
$ npm run dev
$ npm run app

So there's no problem and I can run properly the hyper from npm run app, but how can i install that hyper on my arch linux that can recognize as a app from repository that i built?

**Comment by LabhanshAgrawal** [comment]
you can build the installers using `yarn run dist` or in your case with `npm run dist`
do note that all the scripts are written with yarn in mind, so if there's any issues due to any differences between how yarn and npm handle something then you'd have to use yarn.
after building it you should be able to use the installers. (haven't used arch so don't know which exact distributable you would use)

**Comment by igmt-official** [comment]
okay thank you, I will try yarn
