### ISSUE TITLE
Text rendering broken on v3.2.1 on macOS

### ISSUE THREAD

**Issue by naktinis** [vercel/hyper#6446]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 12.3
- **Hyper.app version**: v.3.2.1 (also tested canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/naktinis/a9c8256e9db23463bc063574a033efe7
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

After upgrading from v3.2.0 to v3.2.1:
- some text became invisible,
- autosuggested text gets a colored background (typically there's no background, it's a translucent macOS window).

Since both of these issues are color-related and happened after the same minor change, I'm assuming they're related, but if not, happy to file separate issues.

Screenshots for invisible text issue comparsion between versions (`htop` command).

Version v3.2.1:
![image](https://user-images.githubusercontent.com/657600/161740237-2fde5b1c-c733-4114-bbeb-3ade4d6147de.png)

Version v3.2.0:
![image](https://user-images.githubusercontent.com/657600/161740534-a84b3f6c-5dd0-43fb-9a86-0bc5f36eb5b3.png)

Colored background issue:
Version v3.2.1
![image](https://user-images.githubusercontent.com/657600/161740782-a636fcd2-9b9e-4427-a367-18320b539d50.png)

Version v3.2.0
![image](https://user-images.githubusercontent.com/657600/161740648-f2470ffa-89f0-4ba5-b079-46ed9112491f.png)

**Comment by LabhanshAgrawal** [comment]
I tried out your config and the issue seems to be from verminal

**Comment by LabhanshAgrawal** [comment]
In this release I've enabled transparent backgrounds with webgl
earlier we'd force canvas renderer with webgl as it didn't support them
but with the newer xterm releases it's usable
since verminal uses vibrancy as well, that might not be playing well with webgl renderer
it seems to work if I disable webgl from config (anyways you would have been using canvas earlier)

You can try different background color settings and verminal specific config or use canvas renderer.
