### ISSUE TITLE
.bash_profile not sourced automatically.

### ISSUE THREAD

**Issue by Miserlou** [vercel/hyper#699]
OSX, fresh install via brew, app updated.

The application window looks great, but it doesn't seem to respect my ~/.bash_profile, so I don't get my colors or aliases out of the box. `source ~/.bash_profile` works as expected. Annoying though.

**Comment by matheuss** [comment]
I can't believe this haven't been noticed by anyone else before 😱 Thanks for reporting!!!

_PS: I can reproduce_

**Comment by hamstu** [comment]
Hmm, seems to be working fine on my end.

Out of curiosity what's in your `~./bashrc` file @Miserlou and @matheuss?

**Comment by Miserlou** [comment]
This is for .bash_profile, not .bashrc. Although I actually do have some exports in my .bashrc, now that I look at it, my .bash_profile is really where the magic happens.

**Comment by matheuss** [comment]
I don't have a `.bashrc` 🤔

**Comment by hamstu** [comment]
@Miserlou Ah yeah — I was just wondering if HyperTerm is sourcing your `.bashrc`, since this is what's in mine and _maybe_ that's why it's sourcing my `.bash_profile` no problem?
```
[ -n "$PS1" ] && source ~/.bash_profile
```

**Comment by timneutkens** [comment]
Hi @Miserlou, I did some researching into this, think I found the issue. Is bash your default terminal, or are you using something like zsh and executing `/bin/bash` after you're in zsh?

Basically what happens when you run `bash` is:
- It doesn't start a login shell. For that you have to use `bash --login`
- Only when your shell is a login shell it sources `~/.bash_profile` otherwise it will try `~/.profile` and if that one is not available `~/.bashrc`. This explains why @hamstu's example is functioning 😄 

More information on this loading behaviour can be found [here](http://hayne.net/MacDev/Notes/unixFAQ.html#shellStartup)

By default when creating a new tab it will load your default login shell using `--login` provided [here](https://github.com/zeit/hyperterm/blob/master/app/config-default.js#L61).

Tested this in Hyperterm and Terminal.app. Could you provide some more insights in how you're using it? Thanks 👍

**Comment by Miserlou** [comment]
Bash is my default shell. This is just a normal OSX install.

**Comment by Miserlou** [comment]
echo $0
-bash

**Comment by timneutkens** [comment]
Could you try to add /bin/bash to the ~/.hyperterm.js config section:
shell: '/bin/bash'

That's how i've tried to reproduce having it as default shell.

**Comment by Miserlou** [comment]
Yeah, that does fix it. I'd either change that default to bash or respect
the default shell in the default Terminal app on OSX for empty strings, or
look at how they're ordered in /etc/shells

**Comment by timneutkens** [comment]
Will have a look at the code again this evening 👍

**Comment by mcornella** [comment]
I can't reproduce. This is my test suite:
```
$ cat .bashrc
echo bashrc
$ cat .bash_profile
echo bash_profile
$ echo $SHELL
/bin/bash
```

If your `$SHELL` isn't bash, `chsh -s /bin/bash` and restart the whole user session so that the shell change is applied.

Now, I'm on Debian Linux so here's what I get with different terminals:

- gnome-terminal: only bashrc is loaded. I'm not using any specific setting to choose the shell, so it appears that it's starting without a login shell.

- hyper terminal: only bash_profile is loaded. So I don't get the same result as you.

So double check that you have the proper shell set up in `/etc/passwd`:
`grep $USER /etc/passwd | cut -d':' -f7`.

If that does indeed return the proper bash shell, I see two possible problems:

- The default shellArgs are not correct. This is what I have in the `hyper.js` file: 
  ```js
shellArgs: ['--login']`
```
  Maybe that has a different value.

- The returned shell by [`default-shell`](https://www.npmjs.com/package/default-shell) is wrong. I seriously doubt that because I get the right output and it has been severely tested. But you can test it yourself. Make and cd into a test folder and run:
  ```
$ npm install default-shell
$ node -e 'console.log(require("default-shell"))'
```

- If neither of those things is right, it's possible that a plugin is changing either the `shell` or `shellArgs` values: see [this line where config is being decorated by plugins](https://github.com/zeit/hyper/blob/26701d4/app/index.js#L70). If that's the case, maybe you can comment all plugins and get the proper behavior, and then later on comment one by one to find the culprit.

  I have to say that if it turns out to be this one, I have to severely stress that this is a security hole and it should be fixed ASAP since I [can't find code that limits which parts of the config](https://github.com/zeit/hyper/blob/26701d4/app/plugins.js#L326-L337) can be set by plugins. I haven't looked all that much to be honest, so I could be wrong.

**Comment by still-dreaming-1** [comment]
It's not sourcing my .bashrc like what normally happens with the Teriminal application. I tried setting the path to bash directly in the shell setting, but that didn't help. I tried removing the entire shellArs option, but that didn't help. Is there at least a workaround to manually source a file upon starting Hyper? I'm using the Solus OS.

**Comment by davidtcdeveloper** [comment]
Same happening here, running in Ubuntu 16.10. Please let me know if you need more data.

**Comment by davidtcdeveloper** [comment]
Updated to 1.3.3 and the problem persists.
Added this line to `.hyper.js` file under `config` object but no profile is loaded anyway.
`shell: '/bin/bash',`

**Comment by booc0mtaco** [comment]
To tag on, I noticed this for contents of `.profile` as well. Bash is my current login shell, but when I installed hyper.app originally, I was using fish. Not sure if switching shells would trigger any different behavior.

In my case, I only had two lines in .profile (for `nvm`) so I moved them to .bash_profile

**Comment by rauleite** [comment]
For me, it works in interactive mode.

`shellArgs: ['-i']
`

**Comment by Rakatashii** [comment]
I'm very new to powershell. I've been borrowing a laptop from my company for less than a week, and that encompasses my entire experience with windows. However, I may have found a solution that works (at least for me).

(inspired by https://superuser.com/questions/1090141/does-powershell-have-any-sort-of-bashrc-equivalent)

In PowerShell:

`New-Item $profile -Type File -Force`

It creates a file called Microsoft.PowerShell_profile.ps1 in a folder called WindowsPowerShell under your Documents folder. Then you can open it with a text editor:

`notepad $profile`

`$bash = [bash | . ~/.bash_profile]`

Now when I execute `bash` in powershell:

I type `env` in bash, and all of the local variables in my bash_profile are present.

Hope this is useful.

**Comment by apoco** [comment]
I'm on Ubuntu 18.04.1 using hyper 2.1.0 and bash and am seeing the same issue. I have tried explicitly specifying `/bin/bash` as the shell and tried using `['--login', '-i']` for command line arguments, and still my `alias ls='ls --color=auto'` in `~/.bashrc` that comes from Ubuntu isn't applied. I'm happy to provide additional details.

**Comment by apoco** [comment]
OK, for my case, I resolved by _just_ using `['-i']` for the shell args, since apparently `~/.bashrc` isn't read for login shells.

**Comment by christopheragnus** [comment]
Hey, I'm having problem of Hyper not sourcing my `~/.bashrc` file as well on Mac OS High Sierra.

**Comment by LabhanshAgrawal** [comment]
seems to fixed by adding `--login` to `shellArgs`

**Comment by burtchensu** [comment]
On ubuntu 20.04, ~/.bashrc not loaded at first, fix by using ['-i'] for the shell args
